version: '2'

services:
 web:
  container_name: wb-php-apache
  build: ./web_server/
  ports:
   - 8889:80
  volumes: 
   - ./www:/var/www/html
  links:
   - db
 db:
  container_name: db-mysql
  build: ./db_server/
  volumes:
   - /var/lib/mysql
  ports:
   - 3307:3306
  environment:
   MYSQL_ROOT_PASSWORD: password
   MYSQL_USER: admin
   MYSQL_PASSWORD: password
   MYSQL_DATABASE: db_dist
